fos_rest:
  format_listener:
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
      - { path: '^/', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }

  exception:
    exception_controller: 'fos_rest.exception.controller:showAction'
    codes:
      Doctrine\ORM\EntityNotFoundException: 404
      \LogicException: 400
      \DomainException: 400
    messages:
      Doctrine\ORM\EntityNotFoundException: true
      \LogicException: true
      \DomainException: true