vich_uploader:
  db_driver: orm

  mappings:
    attachment_file:
      uri_prefix: /uploads
      upload_destination: '%kernel.project_dir%/public/uploads'
#      directory_namer:
#        service: vich_uploader.namer_directory_property
#        options: {date_time_format: 'Y_d_m'}

      delete_on_remove: true